parameters:
    database_driver: pdo_mysql
    database_host: www20.subdomain.com
    database_port: null
    database_name: spotted
    database_user: user2589130
    database_password: spotted2013
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: de
    secret: ca14949e5ba18bf18dea9104cc836248b
    database_path: null
